/* 
 * LUIS Endpoint API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

namespace Ee.Rockit.LuisClient.Test
{
    using Ee.Rockit.LuisClient.Api;
    using NUnit.Framework;

    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DefaultApiTests
    {
        private LuisApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new LuisApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DefaultApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DefaultApi
            //Assert.IsInstanceOfType(typeof(DefaultApi), instance, "instance is a DefaultApi");
        }

        
        /// <summary>
        /// Test V20ResponseGetPredictionsFromEndpoint
        /// </summary>
        [Test]
        public void GetPredictionsFromEndpointTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string appId = null;
            //string q = null;
            //decimal? timezoneOffset = null;
            //bool? verbose = null;
            //bool? spellCheck = null;
            //bool? staging = null;
            //instance.V20ResponseGetPredictionsFromEndpoint(appId, q, timezoneOffset, verbose, spellCheck, staging);
            
        }
        
        /// <summary>
        /// Test V20ResponseGetPredictionsFromEndpointPost
        /// </summary>
        [Test]
        public void GetPredictionsFromEndpointPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string appId = null;
            //decimal? timezoneOffset = null;
            //bool? verbose = null;
            //bool? spellCheck = null;
            //bool? staging = null;
            //string q = null;
            //instance.V20ResponseGetPredictionsFromEndpointPost(appId, timezoneOffset, verbose, spellCheck, staging, q);
            
        }
        
    }

}
